routes/admin.php
<?php

use App\Http\Controllers\Admin\Auth\ChangePasswordController;
use App\Http\Controllers\Admin\Auth\LoginController;
use App\Http\Controllers\Admin\Auth\MyAccountController;
use App\Http\Controllers\Admin\Auth\RegisterController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\VendorController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::redirect('/admin', '/admin/dashboard');
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function() {


/*
|--------------------------------------------------------------------------
| Authentication Routes | LOGIN | REGISTER
|--------------------------------------------------------------------------
*/

Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'login'])->name('login.submit');
Route::post('logout', [LoginController::class, 'logout'])->name('logout');

Route::get('register', [RegisterController::class, 'showRegisterForm'])->name('register');
Route::post('register', [RegisterController::class, 'register'])->name('register.submit');

/*
|--------------------------------------------------------------------------
| Dashboard Route
|--------------------------------------------------------------------------
*/

Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

/*
|--------------------------------------------------------------------------
| User managemebnt > Vendors Route
|--------------------------------------------------------------------------
*/
Route::resource('vendors', VendorController::class);

/*
|--------------------------------------------------------------------------
| User managemebnt > Customers Route
|--------------------------------------------------------------------------
*/
Route::resource('customers', CustomerController::class);

/*
|--------------------------------------------------------------------------
| Settings > My Account Route
|--------------------------------------------------------------------------
*/
Route::resource('my-account', MyAccountController::class);

/*
|--------------------------------------------------------------------------
| Settings > Change Password Route
|--------------------------------------------------------------------------
*/
Route::get('change-password', [ChangePasswordController::class,'changePasswordForm'])->name('password.form');

Route::post('change-password', [ChangePasswordController::class,'changePassword'])->name('change-password');



});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/admin/sections/flashmessage.blade.php
@if ($message = Session::get('success'))
<div class="alert alert-success" role="alert">
	<i class="flaticon-tick-inside-circle"></i> <strong>Well done!</strong> {{ $message }}
</div>
@endif


@if ($message = Session::get('delete'))
<div class="alert alert-danger" role="alert">
	<i class="flaticon-alert-1"></i> <strong>Oh snap!</strong> {{ $message }}
</div>
@endif


@if ($message = Session::get('warning'))
<div class="alert alert-warning" role="alert">
	<i class="flaticon-alert"></i> <strong>Warning!</strong> {{ $message }}
</div>
@endif


@if ($message = Session::get('info'))
<div class="alert alert-info" role="alert">
	<i class="flaticon-information"></i> <strong>Heads up!</strong> {{ $message }}
</div>
@endif


@if ($errors->any())
<div class="alert alert-danger" role="alert">
	<i class="flaticon-alert"></i> <strong>Warning! Please check all form fields below.</strong> {{ $message }}
</div>
@endif

resources/views/admin/sections/header.blade.php
    <!-- Navigation Bar -->
    <nav class="navbar ms-navbar">

        <div class="ms-aside-toggler ms-toggler pl-0" data-target="#ms-side-nav" data-toggle="slideLeft">
          <span class="ms-toggler-bar bg-primary"></span>
          <span class="ms-toggler-bar bg-primary"></span>
          <span class="ms-toggler-bar bg-primary"></span>
        </div>

        <div class="logo-sn logo-sm ms-d-block-sm">
          <a class="pl-0 ml-0 text-center navbar-brand mr-0" href="index.html"><h3 class="ms-text-primary">ADMIN </h3> </a>
        </div>

        <ul class="ms-nav-list ms-inline mb-0" id="ms-nav-options">


          <li class="ms-nav-item ms-nav-user dropdown">
            <a href="#" id="userDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <img class="ms-user-img ms-img-round float-right" src="{{ asset('assets/img/avatar.png') }}" alt="people"> </a>
            <ul class="dropdown-menu dropdown-menu-right user-dropdown" aria-labelledby="userDropdown">
              <li class="dropdown-menu-header">
                <h6 class="dropdown-header ms-inline m-0"><span class="text-disabled">Welcome {{Auth::guard('admin')->user()->firstname}} {{Auth::guard('admin')->user()->lastname}}</span></h6>
              </li>
              <li class="dropdown-divider"></li>
              <li class="ms-dropdown-list">
                <a class="media fs-14 p-2" href="{{route('admin.my-account.edit', Auth::guard('admin')->id())}}"> <span><i class="flaticon-gear mr-2"></i> My Account</span> </a>
              </li>
              <li class="dropdown-menu-footer">
                <a class="media fs-14 p-2" href="{{route('admin.password.form')}}"> <span><i class="flaticon-security mr-2"></i> Change Password</span> </a>
              </li>
              <li class="dropdown-divider"></li>

              <li class="dropdown-menu-footer">
                <a class="media fs-14 p-2" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"> <span><i class="flaticon-shut-down mr-2"></i> Logout</span> </a>
                <form id="logout-form" action="{{ 'App\Models\Admin' == Auth::getProvider()->getModel() ? route('admin.logout') : route('logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
              </li>
            </ul>
          </li>
        </ul>

        <div class="ms-toggler ms-d-block-sm pr-0 ms-nav-toggler" data-toggle="slideDown" data-target="#ms-nav-options">
          <span class="ms-toggler-bar bg-primary"></span>
          <span class="ms-toggler-bar bg-primary"></span>
          <span class="ms-toggler-bar bg-primary"></span>
        </div>

      </nav>

resources/views/admin/sections/loader.blade.php
<!-- Preloader -->
<div id="preloader-wrap">
    <div class="spinner spinner-8">
      <div class="ms-circle1 ms-child"></div>
      <div class="ms-circle2 ms-child"></div>
      <div class="ms-circle3 ms-child"></div>
      <div class="ms-circle4 ms-child"></div>
      <div class="ms-circle5 ms-child"></div>
      <div class="ms-circle6 ms-child"></div>
      <div class="ms-circle7 ms-child"></div>
      <div class="ms-circle8 ms-child"></div>
      <div class="ms-circle9 ms-child"></div>
      <div class="ms-circle10 ms-child"></div>
      <div class="ms-circle11 ms-child"></div>
      <div class="ms-circle12 ms-child"></div>
    </div>
  </div>

resources/views/admin/sections/sidebar-left.blade.php
 <!-- Overlays -->
 <div class="ms-aside-overlay ms-overlay-left ms-toggler" data-target="#ms-side-nav" data-toggle="slideLeft"></div>
 <div class="ms-aside-overlay ms-overlay-right ms-toggler" data-target="#ms-recent-activity" data-toggle="slideRight"></div>

 <!-- Sidebar Navigation Left -->
 <aside id="ms-side-nav" class="side-nav fixed ms-aside-scrollable ms-aside-left">

   <!-- Logo -->
   <div class="logo-sn ms-d-block-lg">
     {{-- <a class="pl-0 ml-0 text-center" href="index.html"> <img src="https://via.placeholder.com/216x62" alt="logo"> </a> --}}
     <a class="pl-0 ml-0 text-center" href="{{ route('admin.dashboard') }}"><h3 class="ms-text-primary">ADMIN </h3></a>
   </div>

   <!-- Navigation -->
   <ul class="accordion ms-main-aside fs-14" id="side-nav-accordion">
     <!-- Dashboard -->
     <li class="menu-item">
       <a href="{{ route('admin.dashboard') }}" >
         <span><i class="material-icons fs-16">dashboard</i>Dashboard </span>
       </a>
     </li>
     <!-- Dashboard -->

     <!--- User Management -->

     <li class="menu-item">
        <a href="#" class="has-chevron" data-toggle="collapse" data-target="#user-management" aria-expanded="false" aria-controls="user-management">
          <span><i class="fas fa-users"></i>User Management</span>
        </a>
        <ul id="user-management" class="collapse" aria-labelledby="user-management" data-parent="#side-nav-accordion">
          <li> <a href="{{route('admin.vendors.index')}}">Vendors</a> </li>
          <li> <a href="{{route('admin.customers.index')}}">Customers</a> </li>
        </ul>
      </li>
     <!-- User Management -->

     <!--- Settings -->
     <li class="menu-item">
        <a href="#" class="has-chevron" data-toggle="collapse" data-target="#settings" aria-expanded="false" aria-controls="settings">
          <span><i class="flaticon-gear"></i>Settings</span>
        </a>
        <ul id="settings" class="collapse" aria-labelledby="settings" data-parent="#side-nav-accordion">
          <li> <a href="{{route('admin.my-account.edit', Auth::guard('admin')->id())}}">My Account</a> </li>
          <li> <a href="{{route('admin.password.form')}}">Change Password</a> </li>
        </ul>
      </li>
      <!-- Settings -->
   </ul>


 </aside>